"""Audit event publishing — Security Spec §6.2, Audit Spec v1.1 §2.1."""

from __future__ import annotations

import json
import logging
import uuid
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone

_audit_logger = logging.getLogger("earp.audit")


@dataclass
class AuditEvent:
    """Audit event aligned with Audit Spec v1.1 §2.1 — 11 fields."""

    source: str                              # MUST  e.g. "security", "runtime"
    event_type: str                          # MUST  e.g. "AUTH_EXPIRED"
    tenant_id: str                           # MUST  tenant scope
    user_id: str                             # MUST  user identity ("" for system events)
    action: str                              # MUST  e.g. "connector_auth"
    result: str                              # MUST  "success" | "failure" | "pending"

    # Auto-generated by publish_audit_event()
    log_id: str = field(default="", init=False)
    timestamp: str = field(default="", init=False)

    # SHOULD fields
    execution_id: str | None = None
    subject: str | None = None
    detail: dict | None = None


def publish_audit_event(event: AuditEvent) -> None:
    """Publish a standardized audit event.

    Writes JSON-serialized event to logger 'earp.audit' at INFO level.
    Auto-generates log_id (UUID4) and timestamp (ISO 8601 UTC).

    NOTE: This function modifies 'event' in place (sets log_id + timestamp).
    The same event instance should NOT be published more than once.
    """
    event.log_id = str(uuid.uuid4())
    event.timestamp = datetime.now(timezone.utc).isoformat()

    data = asdict(event)
    json_str = json.dumps(data, ensure_ascii=False, default=str)
    _audit_logger.log(logging.INFO, json_str)
